### ISSUE TITLE
It seams this game cannot running?

### ISSUE THREAD

**Issue by yifanes** [nilsso/LuaGame#1]
love version 0.9
when I use:
open -a love LuaGameBak

I just see a black screen. Can you help me to run this game?(I am a new luaer and love user)

**Comment by nilsso** [comment]
Yeah it's pretty broken. I was working on it at the time for a class, and pushed whatever my last changes at the time were, which obviously were non-functioning.

**Comment by yifanes** [comment]
o,thanks
